### ISSUE TITLE
Freezes whtn two strategies act quickly

### ISSUE THREAD

**Issue by cyberklezmer** [cyberklezmer/marketsim#6] opened 2022-03-08 09:19 UTC
Having two strategies who quickly run their loops (no waiting) leads to freeze (in run, commenting wait out does not help)

Please see branch  freezeswiththwoquickstrategies

When those strategies are replaced by some slowly acing ones (l1, l2 in main), everything works well.

**Comment by vrka** [comment] 2022-03-16 13:50
Duplicate of #9

**Closed as completed by vrka** 2022-03-16 13:50 UTC
